---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - cloudwatch_region is defined
      - domain_name is defined
      - cloudwatch_log_group is defined
      - accounting_email is defined
      - main_email is defined
      - website_email is defined
      - website_email_password is defined
      - aws_secret_access_key is defined
      - aws_access_key_id is defined

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "namelivia/{{ application_name }}:latest"
    memory: "200MB"
    pull: true
    cleanup: true
    restart_policy: "always"
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}"
    exposed_ports:
      - "80"
    env:
      VIRTUAL_HOST: "{{ domain_name }}"
      LETSENCRYPT_HOST: "{{ domain_name }}"
      VIRTUAL_PORT: "80"
      ACCOUNTING_EMAIL: "{{ accounting_email }}"
      MAIN_EMAIL: "{{ main_email }}"
      WEBSITE_EMAIL: "{{ website_email }}"
      WEBSITE_EMAIL_PASSWORD: "{{ website_email_password }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
